language: minimal

services:
  - docker

before_script:
- chmod a+w -R .

script:
- IMG_VER=0.13.0_r1 ./scripts/dist_build.sh

deploy:
  provider: pages
  local_dir: app/dist
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
